electron/website

docusaurus.config.js
As we're not focusing on the blog for this initial MVP, let's disable the plugin and remove references to the blog from the navigation. Note that the `prebuild` script remains unchanged.
Ref #2
=> chore: disable blog

README.md, scripts/pre-build.js, scripts/tasks/download-docs.js
This PR allows developers to pass a parameter to indicate where in the
file system the `prebuild` script should look for the documentation. It
assumes it is a clone of `electron/electron` so the content should be
under a `/docs` folder. E.g.:
```console
yarn prebuild ../electron
```
In the future there might be a `watch` option enabled by default. This
is the MVP for #4.
Fix #4
=> build: allow building from local electron/electron

.vscode/launch.json, create-electron-documentation/index.js, create-electron-documentation/package.json, create-electron-documentation/readme.md, create-electron-documentation/templates/documentation.md, create-electron-documentation/templates/fiddle/index.html, create-electron-documentation/templates/fiddle/main.js, create-electron-documentation/templates/fiddle/preload.js, create-electron-documentation/templates/fiddle/renderer.js
Add the code for the package `create-electron-documentation` to help
writers of Electron documentation scaffold their examples faster and
following good patterns (using `sandbox` and `contextBridge`).
Once published the developers will use it by calling
```console
npm create electron-documentation
```
From a folder under the main Electron documentation folder.
Fix #12
https://user-images.githubusercontent.com/606594/116306611-208def00-a75a-11eb-8849-fc789b83b357.mp4
=> feat: add `create-electron-documentation` package

create-electron-documentation/index.js, create-electron-documentation/package.json
Without the `bin` property in `package.json` and `#!` at the top of
`index.js` the command `npm create electron-documenation` does not
work properly.
=> fix: bin info in `create-electron-documentation`

docusaurus.config.js
Enable docsearch module with provided configuration by algolia.
Currently the search does not seem to work when `contextSearch` is
enabled. This seems to be a temporary issue per Clement's mail:
> As the DocSearch plugin is not active yet, you won't be able to use
the Docusaurus `contextualSearch` option until next crawl.
While this feature is not necessary (there are no versioned docs),
it seems like the search results page has it enabled by default
always ([1]) so might as well have it enabled everywhere to make sure it
works.
[1]: https://github.com/temporalio/documentation/pull/357/files#r616656533
Ref: https://github.com/facebook/docusaurus/issues/3805
Part of #2
=> feat: enable docsearch

create-electron-documentation/package.json, create-electron-documentation/templates/documentation.md, scripts/tasks/add-frontmatter.js
With the update to .75 the titles are hidden and `hide_title` has to be
disabled. It was enabled initially because otherwise titles were
duplicated (one from frontmatter, the other from the markdown).
=> fix: show titles in docs

docusaurus.config.js, scripts/pre-build.js, scripts/tasks/copy-new-content.js, scripts/tasks/how-to-examples.md, sidebars.js
Add the top navigation link "Examples" and a new page that explains how
to acquire Fiddle and run the examples available in the sidebar.
Partial work on #2
=> feat: add "Examples" navigation link

.env.example, .github/workflows/test.yml, .github/workflows/update-docs.yml, .gitignore, .vscode/extensions.json, .vscode/launch.json, README.md, jest.config.js, package.json, scripts/__tests__/process-doc-changes.js, scripts/__tests__/update-pinned-version.js, scripts/pre-build.js, scripts/process-docs-changes.js, scripts/tasks/download-docs.js, scripts/update-pinned-version.js, scripts/utils/__tests__/git-commands.js, scripts/utils/execute.js, scripts/utils/git-commands.js, yarn.lock
This commit adds support to update the content when there is a change
upstream by:
- Adding a webhook handler to redirect `push` and `release` events from
`electron/electron` to this repo.
- Adding a GitHub action that responds to `repository_dispatch` events
comming from the previous webhook.
More information can be found in #19
Fix #19
=> build: update content when upstream changes

src/transformers/fiddle-embedder.js
Links to fiddle from the doc-site are breaking because they are not including the `v` in the ref. This is a simple fix for that.
cc @erickzhao
=> fix: fiddle links should include the v in the version tag

src/transformers/fiddle-embedder.js
Add support for custom parameterization in the fiddle's code block header.
Example:
````
```javascript fiddle='docs/fiddles/features/keyboard-shortcuts/web-apis|focus=renderer.js'
```
````
This will default the focused tab to `renderer.js`.
To minimize focus issues as fiddles are changed, if the provided file is not found a compile-time error will occur.
Fixes: #34
cc: @erickzhao
=> feat: allow different files to be focused in an embedded fiddle

docusaurus.config.js, scripts/tasks/add-frontmatter.js
If a page has the same name as the folder where it is, it will become
the landing page for that section. E.g.: `/security/security.md` will be
available via `/security` instead of `/security`.
Also add the sections `Performance` and `Security` to the footer
navigation to increase awareness.
=> feat: navigation improvements

scripts/tasks/md-fixers.js
Fixes #56
In the `prebuild` script, we have a step that transforms the raw markdown content from our API docs to work with MDX (ref #3).
https://github.com/electron/electronjs.org-new/blob/5a8d040ade644377220775ea2f2ddb484567c7a8/scripts/tasks/md-fixers.js#L39-L74
We trim the final string output in this transformation, which inadvertently resets all leading whitespace and flattens all Markdown lists in the API docs.
This PR uses `trimEnd()` instead of `trim()` to only remove trailing whitespace instead.
=> fix: only trim trailing spaces for API markdown mod

docusaurus.config.js
=> fix: never highlight "Examples" in navbar

package.json, yarn.lock
See their changelog: https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.4
Cool stuff we get for free with this update:
* Improved mobile UX
* Back to top button
* `_` prefixed folders will now be ignored for content purposes
=> chore: bump Docusaurus to 2.0.0-beta4

sidebars.js
The `Desktop Environment Integration` was removed upstream, which broke builds late last week.
=> fix: remove deprecated doc from sidebar

docusaurus.config.js, i18n/en-US/docusaurus-theme-classic/navbar.json
Closes #73 
Adds an external link to https://releases.electronjs.org
=> feat: link to external Releases homepage in navbar

docusaurus.config.js, package.json, src/components/APIStructurePreview.jsx, src/components/APIStructurePreview.module.scss, src/transformers/api-structure-previews.js, yarn.lock
Closes #116
Kind of like #87, except it adds a tooltip for any structure in `docs/api/structures/*.md` when referenced in another document.
https://user-images.githubusercontent.com/16010076/138810316-ff9d2342-cf2c-498e-8652-1c3355c11a07.mp4
=> feat: add API Structure tooltips to the docs

blog/electron-15-0.md
Looks like the M94 New In Chrome blog post published 
https://developer.chrome.com/blog/new-in-chrome-94/
cc @electron/wg-releases
=> chore: update M94 blog post link

blog/electron-16-0.md
Initial draft of Electron 16 blog post
@electron/wg-releases , @ckerr 
Please add a comment for items you think we should highlight in the blog post.
Merge target: Nov 16th, after 16.0.0 releases successfully
⚠️ do not merge until the following are completed ⚠️
=> chore: Electron 16 blog post

blog/spectron-deprecation-notice.md
This PR adds a formal blog announcing Spectron's deprecation, aiming for release in early December.
=> docs: add Spectron deprecation announcement

.github/workflows/build-and-deploy.yml
We've been getting errors in  many of our workflows recently with the following errors:
```
workflow is invalid: secret name `GITHUB_TOKEN` within `workflow_call` can not be used since it would collide with system reserved name
```
See: https://github.com/electron/electronjs.org-new/actions/runs/1651559030
I think this change makes sense as per GitHub's ["Automatic token authentication"](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) documentation.
> An action can access the GITHUB_TOKEN through the github.token context even if the workflow does not explicitly pass the GITHUB_TOKEN to the action. 
I'm guessing this is because the GITHUB_TOKEN is being provided by Actions and we don't need to provide it in the `secrets` field. Cherry-picking this commit …
=> build: remove `GITHUB_TOKEN` from user secrets

.github/workflows/update-docs-branch.yml, .github/workflows/update-docs.yml
Looks like the `update_docs` action is encountering issues.
Ref #156
=> build: remove GITHUB_TOKEN from update secrets

docs/latest/api/content-tracing.md, docs/latest/api/crash-reporter.md, docs/latest/api/structures/trace-config.md, docs/latest/development/coding-style.md, docs/latest/tutorial/installation.md, docs/latest/tutorial/notifications.md, docs/latest/tutorial/sandbox.md, scripts/tasks/md-fixers.js
Fixes #161
We map any link with a `path.basename` matching an existing Electron doc to that Electron doc. This is a hack because we force the docs to have `/latest` in their URL. This causes links with common names such as `README.md` to get mapped to the Electron link by accident.
=> fix(prebuild): only prefix electron docs

src/components/APIStructurePreview.module.scss
Based on some internal feedback, this PR changes the colours of API structure tooltip indicators from red to blue to be less aggressive.
=> style: tone down colours for API structure tooltips

blog/electron-17-0.md
Initial draft of Electron 17 blog post
@electron/wg-releases , @VerteDinde, @sofianguy 
Please add a comment for items you think we should highlight in the blog post.
Merge target: Feb 1st, after 17.0.0 releases successfully
⚠️ do not merge until the following are completed ⚠️
=> chore: Electron 17 blog post

blog/12-week-cadence.md, docs/latest/tutorial/automated-testing.md, docs/latest/tutorial/ipc.md, docs/latest/tutorial/security.md, scripts/tasks/md-fixers.js
This fixes the current spacing with the admonitions so Crowdin doesn't change the format and we can actually build the translated documents.
It also adds a new fixer just in case we don't add the spaces again upstream.
=> fix: admonitions for crowdin

docusaurus.config.js, src/transformers/api-options-class.js
This transformer adds `class="electron-api-options-list"`
to any \<li\> element that starts with <code>options</code>.
This is for future use in the Algolia crawler to refine the
number of list items we want to store in our search index.
=> feat(md): add class name to `options` list items

docs/latest/tutorial/code-signing.md, scripts/tasks/md-fixers.js
We were replacing the wrong regex portion here during the prebuild step.
=> fix: proper str replace in multiline image title

.github/workflows/build-and-deploy.yml, .github/workflows/pull-request.yml, .github/workflows/push-main.yml, .github/workflows/update-i18n-deploy.yml, package.json, yarn.lock
Docusaurus 2.0.0-beta.21 is a fix-only polish upgrade that doesn't change any APIs. However, it does require NodeJS 16.14, so we need to upgrade our GH Actions accordingly. This should be pretty safe to merge.
=> build(deps): upgrade docusaurus to beta.21

src/css/custom.scss
Ref https://github.com/facebook/docusaurus/pull/7176
Looks like the upstream way of changing code block highlights changed in [v2.0.0-beta.19](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.19) and I didn't catch it.
This makes code highlights look better again.
=> fix(css): use newer code line highlight styles

src/css/custom.scss
Necessary for now because the font that we use for the monospace `code` in the docs does not come with a semi-bold (500 weight) version.
=> style: make doc markdown links bold

scripts/tasks/create-sidebar.js, sidebars.js
Move the "Tutorial" category towards the top.
Ignore "support".
=> chore: sidebar improvements

src/pages/home/_components/AppsGrid.jsx, src/pages/home/_components/TechnologiesGrid.jsx
This API will be removed in a future release of Docusaurus (ref https://github.com/facebook/docusaurus/pull/6930)
=> refactor: stop using deprecated `isDarkTheme` API

docs/latest/tutorial/tutorial-4-adding-features.md
The link currently displays as follows (see [here](https://www.electronjs.org/docs/latest/tutorial/tutorial-adding-features#how-to-examples)):
To get started, check out the [How-To Examples][how-to] doc.
=> Fix broken link to examples in tutorial 4

blog/electron-20.md
The 20.0.0 blog post.
CC @electron/wg-releases
=> docs: add electron 20 blog post

blog/electron-20-0.md
Does what it says on the tin - should fix the E20 blog deploy
=> fix: update file name and date/time for E20 blog

src/pages/fiddle/index.jsx
The [hyperlink incorrectly points](https://github.com/electron/electronjs.org-new/blob/main/src/pages/fiddle/index.jsx#L229) to electron forge, leading to a 404 (https://www.electronjs.org/electronforge.io) - 
<strong>Note:</strong> This change is not tested (but I assume it to be correct!) since I am unable to build the website locally. It always get stuck at 46% while building the markdown - 
Any ideas?
=> fix: rectify the hyperlink pointing to electron forge

docs/latest/tutorial/tutorial-4-adding-features.md
This reverts commit 21325bee69f1d18df46390d48a39827a3b12f3b5.
This should be amended upstream in `electron/electron` rather than in this repo since future updates will overwrite this change.
cc @molant
=> chore: Revert "Fix broken link to examples in tutorial 4"

package.json, yarn.lock
Fixed: https://github.com/electron/electronjs.org-new/issues/250
`@crowdin/cli` fixed this bug in 3.7.9. See: https://github.com/crowdin/crowdin-cli/commit/4e7d9320c08f412d6fbe70d13076564fe7469cbb
=> fix: translation not working

blog/electron-20-0.md, blog/electron-21-0.md, blog/v8-memory-cage.md
Electron 17 blog post
@electron/wg-releases , @ckerr , @georgexu99
Please add a comment for items you think we should highlight in the blog post.
Merge target: Sept 27th, after 21.0.0 releases successfully
=> chore: Electron 21 blog post

blog/v8-memory-cage.md
Adds a link to the Electron issue tracker discussion and fixes a typo in the version number.
cc @nornagon
=> blog: update memory cage blog

blog/forge-v6-release.md
initial PR to get things going ahead of forge v6 release.
- I refer to forge v6 as: Electron Forge v6, Forge, Forge v6 let me know if this should be standardized
- breaking changes needs to be fleshed out
=> chore: Forge v6 blog post

docusaurus.config.js
Fixes the banner link for Forge's blog post (it's currently 404'ing because it tries to redirect based on whatever page you're on at the time - e.g. `electronjs.org/docs/blog` instead of just `electronjs.org/blog`)
=> fix: update Forge's banner link

yarn.lock
```
npx browserslist@latest --update-db
Latest version:     1.0.30001429
Installed versions: 1.0.30001317, 1.0.30001335
Removing old caniuse-lite from lock file
Installing new caniuse-lite version
```
=> chore(deps): update caniuse-lite version

src/css/custom.scss, src/theme/DocPage/Layout/index.js, src/theme/DocPage/Layout/styles.module.css
* Moves the docs nav closer to the actual doc content
* Fewer words per line
* More line spacing
* More consistent color scheme
|   Before   |  After   |
|-----------|-------|
|     ![image](https://user-images.githubusercontent.com/16010076/200697146-f688c8e6-44b0-4c93-934a-798e4f0a46f5.png)  |    ![image](https://user-images.githubusercontent.com/16010076/200697083-b7b21ab2-324d-4a2c-955a-8ae8f1266767.png)   |
=> style: css improvements

src/components/APIStructurePreview.module.scss, src/transformers/api-structure-previews.js
Fixes #295 
Adds a second pass to the AST walker to find and replace reference-style links. These were previously skipped in the visitor check since we only checked for `link`-type nodes.
For more information on Node types for the Markdown AST, see the [mdast spec](https://github.com/syntax-tree/mdast).
```md
[Example link][1]
[1]: https://example.com
```
=> fix(api-structures): support reference-style links

src/pages/apps/apps.module.scss
When running `yarn start` on the website repo, the build runs but with the following warning emitted from webpack:
```
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/Users/erick.zhao/Developer/electron/electronjs.org-new/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[11].oneOf[0].use[1]!/Users/erick.zhao/Developer/electron/electronjs.org-new/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[11].oneOf[0].use[2]!/Users/erick.zhao/Developer/electron/electronjs.org-new/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[11].oneOf[0].use[3]!/Users/erick.zhao/Developer/electron/electronjs.org-new/src/pages/apps/apps.module.scss': No serializer registered for Warning
<w> while serializing …
```
=> style: fix webpack warning for `end` property.

src/css/custom.scss
Fixes #301
The mobile menu was broken here!
=> fix(css): remove `backdrop-filter` prop from navbar styles

docusaurus.config.js
Since we landed the Docusaurus-based homepage, we can now remove the hard-coded link to https://electronjs.org set up in our navbar logo.
=> chore: remove hard-coded url from navbar link

blog/electron-22-0.md
Electron 22 blog post
@electron/wg-releases 
Please add a comment for items you think we should highlight in the blog post.
Merge target:  Nov 29th, after 22.0.0 releases successfully
=> chore: Electron 22 blog post

.github/workflows/update-docs.yml
I think there was a typo here so our publishing doesn't actually work when the docs get updated.
See the job output syntax: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-defining-outputs-for-a-job
=> build: fix expression for deploying site on docs update

package.json, yarn.lock
We're kind of just dancing around ESM-only module versioning here.
=> build: fix resolution for latest-version

sidebars.js
Since https://github.com/electron/electron/pull/30720, `desktopCapturer` has only been available in the main process. That changed shipped in v17, so no supported versions have it in the renderer process, this is safe to fix.
=> fix: desktopCapturer is main-process-only module

src/transformers/api-structure-previews.ts
Fixes this error:
```
TypeError: Cannot read properties of undefined (reading 'type')
at runMicrotasks (<anonymous>)
TypeError: Cannot read properties of undefined (reading 'type')
at runMicrotasks (<anonymous>)
TypeError: Cannot read properties of undefined (reading 'type')
at runMicrotasks (<anonymous>)
```
=> fix(api-structures): guard against empty arrays

README.md, i18n.md
Updates the old README we had from the beta.electronjs.org stage, and ports over the old [CONTRIBUTING.md from electron/i18n](https://github.com/electron/i18n/blob/master/contributing.md).
=> docs: update READMEs

.github/workflows/update-i18n-deploy.yml
Reduces it from 48 times a day to twice a day.
It takes about 15 minutes for all our i18n to build so failures get really noisy.
=> build: reduce i18n deploy frequency

scripts/update-crowdin-glossary.ts
Skips single-word Electron events because these can be common words we want to translate such as `closed` or `quit`.
Orthogonal bugfix: also uses `continue` to skip loop iterations rather than `return`.
=> fix(i18n): add glossary support for multi-word events

blog/forge-v6-release.md
Expected behaviour: open the appropriate page.
Current behaviour (below):
=> docs: update a broken link in the blog page

blog/forge-v6-release.md
NPM needs an additional `--` according to the official [Getting Started Docs](https://www.electronforge.io/)
When trying out the "Getting started" command from the blog post I noticed that the webpack plugin was not correctly added. Using the command from the official website works as expected.
=> fix(blog): fix npm getting started command

scripts/tasks/create-sidebar.ts, sidebars.js
At the moment this is down at the bottom of the sidebar in a duplicated "Tutorial" section, and the page title in the sidebar is awkward, so just remove it all together.
=> fix: remove old support page from sidebar

.github/workflows/update-docs-branch.yml, .github/workflows/update-docs.yml
Changed as per these instructions: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> ci: update usage of deprecated ::set-output

.github/workflows/build-and-deploy.yml, .github/workflows/pull-request.yml, .github/workflows/push-main.yml, .github/workflows/update-docs-branch.yml, .github/workflows/update-docs.yml, .github/workflows/update-governance.yml, .github/workflows/update-i18n-deploy.yml
Updates and pins SHAs for actions, also tightens perms in a few spots. Should clear deprecation warnings on workflow runs.
=> ci: update GitHub actions workflows

blog/electron-23-0.md
=> fix: correct year for Electron 23 blog post

docusaurusConfig.ts
> If you put an HTTPS link in your profile metadata, Mastodon checks if that link resolves to a web page that links back to your Mastodon profile with a special rel=me attribute.
https://docs.joinmastodon.org/user/profile/#verification
=> fix: add `rel=me` for mastodon link

.github/workflows/push-main.yml
This allows the website to update periodically. It's useful for @electron-bot upstream updates (they don't trigger builds due to a GHA limitation) and to refresh information gathered from Docusaurus plugins on build time (governance, showcase, releases).
=> build: add twice a day cronjob

src/transformers/api-structure-previews.ts
In preparation of https://github.com/electron/electron/pull/34633/ landing, exclude certain API structures from showing the hover preview.
=> feat: exclude list for transformers/api-structure-previews

blog/electron-24-0.md
Electron 24 blog post
@electron/wg-releases 
Merge target: after 24.0.0 releases successfully
note: I didn't see any notable huge API changes, therefore for this blog we go back to the e21 blog style where we have no highlighted change. I didn't see any breaking changes either
=> chore: Electron 24 release post

blog/electron-24-0.md
This PR correct the 24 blog post by removing mention of two methods, which weren't actually deprecated.
Fixes https://github.com/electron/website/issues/401
=> chore: remove deprecated methods from 24 blog

blog/electron-24-0.md
Corrects the versions of Node & V8 in the Electron 24 blog post
=> chore: correct node & v8 versions

blog/electron-25-0.md
Electron 25 blog post
@electron/wg-releases 
Merge target: after 25.0.0 releases successfully
release notes link: https://corp.quip.com/5YnnALwP5NUb/e25-release-notes
=> chore: Electron 25 release blog

docusaurusConfig.ts
Ref https://github.com/facebook/docusaurus/pull/8690
We don't actively support `pnpm` across many Electron tools (e.g. https://github.com/electron/forge/issues/2633).
Disable this for now on the website.
=> fix(docs): don't convert npm -> pnpm

src/components/APIStructurePreview.tsx, src/transformers/api-labels.ts
=> fix: show badges in API structure previews

blog/electron-25-0.md
Have to use full URLs in the blog posts when linking to the docs.
=> fix: link to protocol.handle in v25 blog post

.github/workflows/push-main.yml
Turns out that CrowdIn doesn't like updating the same files in parallel, which causes this workflow to hit errors if you merge two commits one after the other:
* https://github.com/electron/website/actions/runs/5613276938/job/15208951083
* https://github.com/electron/website/actions/runs/5613272569/job/15208938247
You can limit concurrency at just the job level, but seems like the best idea is to limit concurrency of this workflow overall since parallel deploys of the website could run into other issues
=> ci: limit concurrency of publish workflow

src/transformers/api-labels.ts
MAS is one of [the supported platform tags by `@electron/docs-parser`](https://github.com/electron/docs-parser/blob/fddaf1a9e515f7c99d465bd604b3f1a2990e5cbe/src/markdown-helpers.ts#L12-L20) and it's used in the `e/e` docs, so let's badge it like the other platforms.
=> fix: badge for MAS tags

src/transformers/api-structure-previews.ts
Follow-up to #431.
The original fix didn't handle i18n well, so this fix:
* Transforms i18n file paths like `/i18n/de/docusaurus-plugin-content-docs/current/latest/api/structures/object.md` to `/de/docs/latest/api/structures/object.md` for the key in the `fileContent` map so that the lookup for links will find them
* Covers the case where you're running a locale (e.g. `yarn start --locale de`) without having downloaded the translations first (via `yarn i18n:download`) - instead of throwing an error on timeout it checks if it's a missing translation and supplies the default locale content
=> fix: API structure previews with i18n

blog/electron-26-0.md
Electron 26 blog post
@electron/wg-releases 
Merge target: after 26.0.0 releases successfully
=> docs: Electron 26 release blog

src/transformers/api-structure-previews.ts
The ["Update i18n deploy" workflow](https://github.com/electron/website/actions/workflows/update-i18n-deploy.yml) is failing intermittently with different errors about timed out waiting for content - the randomness of it makes me think the builds are just a bit slower than expected so this timeout needs to be increased.
=> fix: increase timeout for API structure preview content

src/pages/home/_index.tsx
This PR simply updates the WordPress Desktop capitalization on the home page. It's a nit but I figured why not address it as that capital P is a sticky subject with the WordPress Foundation. 😄
=> fix: Update WordPress capitalization on home

src/pages/fiddle/index.tsx
Ugly hack to fix the download links for Linux-only v0.34.3 release.
=> fix: download links for Fiddle v0.34.3

blog/electron-27-0.md
This PR adds a new blog post for Electron 27.
@electron/wg-releases, @electron/wg-outreach 
Merge target: October 10th, after 27.0.0 releases.
=> docs: add Electron 27 blog post

scripts/tasks/md-fixers.ts
I think this causes issues with the build 🤔
=> fix(md): ensure `</details>` tag is on newline

src/pages/fiddle/index.tsx
Fixes #467. The artifacts for Fiddle end in `-x64.AppImage`, not `-x86_64.AppImage`.
=> fix: correct Fiddle link for x64 AppImage

src/pages/fiddle/index.tsx
Partial revert of #455 (leaves the destructuring of `version` as that's reasonable). No longer needed as we're back to releases on all platforms.
=> fix: remove Fiddle download links hack

src/pages/fiddle/index.tsx
Fixes https://github.com/electron/fiddle/issues/1503
cc @erickzhao
=> fix: Fiddle download links

yarn.lock
Clears a Dependabort alert, but the other can't be cleared until #466 happens.
=> chore: update deps to clear some audit warnings

blog/dec-quiet-period-23.md
This PR updates the 2023 quiet period post to reflect that E28 will still be released on Dec. 5.
=> chore: update quiet period post for E28

blog/2023-ecosystem-eoy-recap.md
This PR adds a blog post for our Ecosystem 2023 year's end recap.
=> docs: Ecosystem 2023 recap blog

blog/electron-28-0.md
This PR adds a new blog post for Electron 28.
@electron/wg-releases, @electron/wg-outreach 
Merge target: December 5th, after 28.0.0 releases.
=> docs: add Electron 28 blog post

blog/electron-28-0.md
This wasn't published until 2023-12-06 and with the original date it sorts below an older blog post, which is confusing.
=> docs: update E28 blog post date

sidebars.js
The new ESM tutorial was grouped into a duplicate 'Tutorial' grouping. Put it under 'Development' which seems like the best fit for the moment.
=> fix: clean up duplicated tutorial sidebar grouping

package.json
The files for these scripts no longer exist, so clean them up.
=> build: remove outdated scripts

blog/electron-28-0.md
We should look into automation around this, we tend to end up with broken links like these in blog posts.
=> fix: link to MessageChannel in v28 blog post

src/theme/prism-include-languages.js
This is in preparation of upstream docs in `e/e` making usage of `cjs` and `mjs` language identifiers in code blocks. Need to add them as aliases for JS so they get syntax highlighting on Docusaurus.
The code changes are a result of [following the official docs](https://docusaurus.io/docs/markdown-features/code-blocks#supported-languages) and running `yarn swizzle @docusaurus/theme-classic prism-include-languages`, then adding the aliases.
=> chore: add cjs and mjs aliases for code block syntax highlighting

.github/workflows/update-docs-branch.yml, .github/workflows/update-docs.yml
The default permissions for `GITHUB_TOKEN` have changed, so update these.
=> ci: update perms for workflow jobs

.github/problem-matchers/docusaurus.json, .github/workflows/build-and-deploy.yml, .github/workflows/update-i18n-deploy.yml
Adds a problem matcher to turn warnings in the Docusaurus build output into warning annotations on the workflow runs so they're more discoverable, and org-wide automation can pick them up.
=> ci: add problem matcher for Docusaurus output

.github/workflows/update-i18n-deploy.yml
Follow-up to #494, we missed one workflow.
=> ci: bump missed workflow to Node.js v20

src/pages/fiddle/index.tsx
This has always been incorrect, I believe.
=> fix: correct download link for Fiddle arm7l AppImage

src/pages/fiddle/index.tsx
v0.36 of Fiddle on macOS was incorrectly named due to a small naming issue inside Forge. This PR ensures that our download links for 0.36 are correct and that people can download it.
@dsanders11 has a PR up to revert it and restore the original name behavior. 
For maintainer context, see these two discussions ([1](https://electronhq.slack.com/archives/CNTJBD467/p1706833617716669), [2](https://electronhq.slack.com/archives/CB389B7MH/p1707159053504549)).
=> fix: Fiddle download links in v0.36

blog/august-2016-roundup.md, blog/electron-37.md, blog/july-2016-roundup.md
I don't think we support this syntax on the website at all anymore (e.g. https://www.electronjs.org/blog/august-2016-roundup), and MDX 3 will explicitly require us to escape these characters in the copy.
=> fix(blog): remove outdated CSS syntax

package.json, yarn.lock
This will fix checking Twitter links in the "Check Blog Links" workflow.
=> build: bump @electron/lint-roller to 1.11.1

blog/electron-29-0.md
This PR adds a new blog post for Electron 29.
@electron/wg-releases, @electron/wg-outreach 
Merge target: February 20th, after 29.0.0 releases.
_Note: The "Check Blog links" job is going to fail until the Chrome 122 announcement blog comes out, a fail there is expected until about Tuesday_
=> docs: add Electron 29 blog post

.gitignore, i18n/readme.md
I don't think this little README file has been touched in a while. :)
=> docs: update i18n/README.md

versions-info.json
Don't think we use this anymore. It points to 22-x-y and there's no way that's relevant. :)
=> chore: delete unused versions-info.json

blog/electron-18.md
**Summarize your changes:**
Fixes #229
Refactored feature highlight for `first-instance-ack` according to [#31460](https://github.com/electron/electron/pull/31460).
=> fix: opposite event description in blog

src/pages/fiddle/index.tsx
Fixes https://github.com/electron/fiddle/issues/1571
We tried to make this self-healing in #507 but the next release ended up being v0.36.2 instead of v0.37.0 (no features 🤷) so this didn't end up working as we'd hoped. The "Check Download Links" scheduled job on the Fiddle repo [ended up catching it as intended](https://github.com/electron/fiddle/actions/runs/8384059849).
=> fix: macOS download links for Fiddle v0.36.2

src/css/custom.scss
--ifm-navbar-item-padding-horizontal variable was never assigned a value
Fixes #369
=> fix: Navbar carets should never appear on a separate line (#369)

.github/workflows/update-docs-branch.yml, .github/workflows/update-docs.yml
Fixes the workflow after #533 which accidentally broke it by not removing the single quotes around `yarn pre-build` when changing to multi-line.
Also updates the workflow to work with manual runs via `workflow_dispatch` so that we can easily re-run any failures.
=> ci: fix docs update workflow

blog/electron-30-0.md
This PR adds a new blog post for Electron 30. @electron/wg-releases, @electron/wg-outreach
Merge target: April 16th, after 30.0.0 releases.
_Note: The "Check Blog links" job is going to fail until the Chrome 122 announcement blog comes out, a fail there is expected until about Tuesday_
=> docs: add Electron 30 blog post

.github/workflows/check-blog-links.yml
Dependabot is convinced this is using an old version (<41) which has a security vulnerability, even though we're using v44. I'm hoping bumping it here will clear the erroneous security alert.
=> ci: bump tj-actions/changed-files version

.eslintrc.js, jest.config.js, package.json, scripts/tasks/create-sidebar.ts, src/theme/DocSidebarItem/Link/index.tsx, tsconfig.json, yarn.lock
This PR migrates to TypeScript 5, which is a prerequisite for upgrading to Docusaurus 3.
- This adds a major version bump to [`@tsconfig/docusaurus`](https://www.npmjs.com/package/@tsconfig/docusaurus?activeTab=code), which now uses the `bundler` module resolution strategy from TS 5.
- `@typescript-eslint` was upgraded to support TS 5.
- This is the smallest major version bump that would allow this to work.
- Note that because this version of `@typescript-eslint` does not support TS 5.4, we're a bit behind in TS versions.
- Removes Jest dependencies since we weren't using them. Can be added back at any point if we add unit tests to the code.
Future work:
- Upgrade ESLint and `@typescript-eslint`
- Upgrade to TS 5.4.5
=> build: upgrade to TypeScript 5.3

docs/latest/api/app.md, docs/latest/api/auto-updater.md, docs/latest/api/base-window.md, docs/latest/api/browser-window.md, docs/latest/api/client-request.md, docs/latest/api/crash-reporter.md, docs/latest/api/ipc-main.md, docs/latest/api/protocol.md, docs/latest/api/push-notifications.md, docs/latest/api/session.md, docs/latest/api/structures/file-path-with-headers.md, docs/latest/api/structures/notification-response.md, docs/latest/api/structures/protocol-request.md, docs/latest/api/structures/protocol-response.md, docs/latest/api/structures/transaction.md, docs/latest/api/structures/user-default-types.md, docs/latest/api/system-preferences.md, docs/latest/api/web-contents.md, docs/latest/api/web-request.md, docs/latest/api/webview-tag.md, package.json, yarn.lock
I removed the `ts-node` dependency in #563, but forgot that we have a bunch of scripts that rely on being run with that package. 🤦
Unfortunately, the move to ES Modules for various packages we rely on made it impossible to just revert the config.
I ran into some issues despite running with the `--esm` flag, and there seem to be some upstream issues with `ts-node` and Node 20: https://github.com/TypeStrong/ts-node/issues/1997
I tried [`tsx`](https://www.npmjs.com/package/tsx) as a drop-in replacement and it seems to work like a charm.
Note that this PR seems to have updated a bunch of docs via the `pre-build` script. I don't know why changes didn't pick this up before, but it seems like all these formatting changes the double whitespaces are present upstream. Might be related to the …
=> fix(build): use `tsx` for build scripts

blog/electron-31-0.md
This PR adds a new blog post for Electron 31. @electron/wg-releases, @electron/wg-outreach
Merge target: June 11th, after 31.0.0 releases.
_Note: The "Check Blog links" job is going to fail until the Chrome 126 announcement blog comes out. A fail is expected until about Tuesday_
=> docs: add Electron 31 blog post

package.json, yarn.lock
This is unused as far as I can determine, so remove it.
=> build: remove unused del dependency

.github/workflows/resolve-pr-release-versions.yml
This is a temporary workflow in support of @piotrpdev's Google Summer of Code work. Long-term this will be removed from this repo and the code will be refactored to live on `electron/release-status`, but for now this is the easiest place to put it such that it can be used immediately. Since it is temporary I've kept it isolated entirely to this one file so it doesn't affect anything else in this repo.
Example snippet of how to fetch the content from the latest workflow run is included below. Requires a GitHub token with `actions: read` perms on `electron/website` repo.
```js
const AdmZip = require('adm-zip');
const AUTH_HEADER = { Authorization: 'Bearer ${{ env.GH_TOKEN }}' };
let resp = await fetch('https://api.github.com/repos/electron/website/actions/artifacts', { headers: AUTH_HEADER …
```
=> ci: temporary workflow to resolve Electron release versions for PRs

docusaurus.config.ts, package.json, patches/@docusaurus+plugin-content-blog+3.4.0.patch, src/theme/BlogSidebar/Desktop/index.tsx, src/theme/BlogSidebar/Desktop/styles.module.css, src/theme/BlogSidebar/Mobile/index.tsx, src/theme/BlogSidebar/Mobile/styles.module.css, src/theme/BlogSidebar/index.tsx, src/theme/README.md, yarn.lock
This PR:
Update: [Docusaurus PR](https://github.com/facebook/docusaurus/pull/10252).
~Note: Do we need to update [CircleCI configs ](https://github.com/ds300/patch-package?tab=readme-ov-file#circleci)for the new patches?~ Updated yarn script to build the patch
=> feat: blog sidebar grouped by year

blog/electron-31-0.md
This is a minor nitpick, but Crowdin doesn't seem to parse this properly so here's an alternative formatting option.
=> blog: replace custom jsx with `<sup>` tag

package.json
I think this option will help us clean out old files that get removed in newer major versions of Electron.
=> build(i18n): delete obsolete files when uploading to crowdin

package.json, scripts/tasks/download-docs.ts, yarn.lock
Replaces `make-dir` with built-in `mkdir` from Node.js, as recommended on https://github.com/sindresorhus/make-dir.
=> chore(prebuild): remove make-dir dependency

.github/workflows/update-docs-branch.yml, .github/workflows/update-docs.yml
Will fix an issue which corrupts images on commit, I think it's bit us once on `gatekeeper.png` in the past.
=> ci: bump dsanders11/github-app-commit-action from v1.4.0 to v1.4.1

src/pages/home/_index.module.scss
Noticed that we had some stray styles in our docs that made certain text sizes larger than others. This PR fixes that.
=> style: default font sizes for docs

.github/workflows/push-main.yml
Hit an issue with nested workflows and permissions. I think this should fix it.
> [The workflow is not valid. .github/workflows/push-main.yml (Line: 30, Col: 3): Error calling workflow 'electron/website/.github/workflows/build-and-deploy.yml@main'. The nested job 'build_and_deploy' is requesting 'actions: read', but is only allowed 'actions: none'.](https://github.com/electron/website/actions/runs/10356949205)
=> ci: try fixing publish job

blog/electron-32-0.md
This PR adds a new blog post for Electron 32. @electron/wg-releases, @electron/wg-outreach
Merge target: August 20th, after 32.0.0 releases.
⚠️ Do not merge until the following are completed ⚠️ 
_Note: The "Check Blog links" job is going to fail until the Chrome 128 announcement blog comes out. A fail is expected until about Tuesday_
=> docs: Electron 32 blog

src/transformers/api-structure-previews.ts
i18n builds sometimes fail with an opaque MDX compilation error. Locally, I am unable to reproduce the error when commenting out the API structure previews.
```
2024-08-28T18:10:44.3503233Z Error: MDX compilation failed for file "/home/runner/work/website/website/i18n/zh/docusaurus-plugin-content-docs/current/latest/api/native-image.md"
2024-08-28T18:10:44.3505973Z Cause: Cannot read properties of undefined (reading 'type')
```
=> fix(api-structure-previews): check arr length

.github/workflows/push-main.yml, .github/workflows/update-i18n-deploy.yml
Adds the ability to manually trigger jobs that we normally run via cron.
=> ci: add `workflow_dispatch` to cron jobs

package.json
This allows us to use cloudflare pages for PR previews instead of the weird heroku app set up we had before 🤷
=> build: set packageManager

src/components/ApiHistoryTable.module.scss
Fixes a bug where the "History" summary wraps words unnecessarily. Only occurs on mobile devices for some reason.
| Before | After |
|:-------:|:------:|
| <img width="200" src="https://github.com/user-attachments/assets/36389956-c76c-45f4-bca7-d2d39555a453" /> | <img width="200" src="https://github.com/user-attachments/assets/f7e0f506-e540-45cc-b3a4-b81829f0d1e5" /> |
=> fix(api-history): summary word wrap

blog/electron-33-0.md
This PR adds a new blog post for Electron 33. @electron/wg-releases, @electron/wg-outreach
Merge target: October 15th, after 33.0.0 releases.
⚠️ Do not merge until the following are completed ⚠️ 
_Note: The "Check Blog links" job is going to fail until the Chrome 130 announcement blog comes out. A fail is expected until about Tuesday_
=> docs: add blog post for Electron 33.0.0 release

package.json, yarn.lock
Also bumps the deep dependency on `express` to clear some security audit warnings.
=> build(deps): docusaurus 3.6.1 upgrade

.github/workflows/update-docs.yml
We snipped this from the script in #327 so it's being unused and we should remove it to avoid confusion.
=> ci: remove unused branch argument to pre-build script

.github/workflows/audit-docs-version.yml
Site only updates on commits which touch `docs/`, so need to search commits rather than use the most recent.
=> chore: tweak docs version audit

yarn.lock
Used `npx uuaw cross-spawn` to bump these.
=> build(deps): bump cross-spawn to partially clear audit

docusaurus.config.ts, scripts/pre-build.ts
Running `yarn pre-build` fails locally otherwise, so this works around it.
=> chore: allow running pre-build without SHA target

.github/workflows/update-docs.yml
Parallel runs of this workflow will fail to commit the new docs updates because HEAD will have moved by the time the commit happens, see [this run](https://github.com/electron/website/actions/runs/12105783880).
This may still have event ordering issues when two merges happen quickly on `e/e`, leading to an older version of the docs being deployed. They'll be fixed in the future when we migrate to publishing tags/releases rather than specific SHAs.
=> ci: limit concurrency of update docs workflow

blog/migrate-to-webcontentsview.md
Previously the `WebContentsView` migration guide/blog post did not mention the changed default background color of `WebContentsView` compared to `BrowserView`'s, this adds a note about that.
Closes [electron/#44914](https://github.com/electron/electron/issues/44914#issuecomment-2513233059)
=> blog: mention background color on WebContentsView

src/theme/DocSidebarItem/Link/index.tsx
Refs https://github.com/facebook/docusaurus/blob/a99586531473678d2c47d8576971e496777fb617/packages/docusaurus-theme-classic/src/theme/DocSidebarItem/Link/index.tsx#L19-L26.
Currently `index="<N>"` is getting added to the sidebar links, which is not valid HTML.
=> fix: don't put index prop on sidebar links

src/theme/DocSidebarItem/Link/index.tsx
Didn't notice the linting warning in #701, so clearing that and this also makes it more clear that we're intentionally including the unused variable.
=> chore: clear linting warning

.github/workflows/audit-docs-version.yml
I think a side effect of #703 is that there are no longer quotes around the values being looked for by the audit, so make them optional.
=> chore: tweak docs version audit to work with latest version

src/pages/community/index.tsx
This got [flagged by the Docusaurus build with a somewhat cryptic warning](https://github.com/electron/website/actions/runs/12363701773/job/34505551503#step:11:12):
```
- "/community/":
- [HTML minifier diagnostic - error] No "p" element in scope but a "p" end tag seen - {"primary_spans":[{"end":14736,"start":14732}],"span_labels":[]}
```
The reason the warning says no `p` element is in scope but it sees a `p` end tag is that the `ul` element closes the `p` element and [is considered to be omitted](https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element):
> A [`p`](https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element) element's [end tag](https://html.spec.whatwg.org/multipage/syntax.html#syntax-end-tag) can be omitted if the …
=> fix: move ul elements outside of p element

blog/node-22-ecosystem-update.md
This PR adds a blog/announcement for our plan to move the ecosystem packages to Node 22
_NOTE: Please hold merging this until Jan 1, 2025_
=> blog: ecosystem node 22 update blog

blog/electron-34-0.md
This PR adds a new blog post for Electron 34. @electron/wg-releases, @electron/wg-outreach
Merge target: January 14th, after 34.0.0 releases.
⚠️ Do not merge until the following are completed ⚠️ 
_Note: The "Check Blog links" job is going to fail until the Chrome 132 announcement blog comes out. A fail is expected until about Tuesday_
=> docs: add electron 34 blog post

sidebars.js
This PR
- removes quickstart from the sidebar
- moves tutorial to be a subsection of `Get Started`
- moves Advanced Installation to the `Development` section
=> chore: rework the get started section

package.json
Avoids the issue of pushing PRs with styles that don't pass the lint check.
=> chore: add styling to precommit hook

docusaurus.config.ts, sidebars.js
So, why the heck even use Electron? Doesn't the operating system already ship with a web view? And in any case, aren't all good apps native apps?
=> docs: Why Electron?

package.json, scripts/tasks/add-frontmatter.ts, scripts/tasks/download-docs.ts, scripts/tasks/md-fixers.ts, scripts/tasks/preprocess-api-history.ts, yarn.lock
This PR stacks on top of #743. Replaces `globby` with the new `fs.glob` introduced in Node 22.
=> refactor: replace `globby` with `fs.glob`

src/css/custom.scss
A less hacky way to avoid the XL markdown width that Docusaurus comes with by default. Makes the DocCardList view more pleasant and aligns our Markdown content width with our buttons.
| Before | After |
|--------|-------|
|![image](https://github.com/user-attachments/assets/1b254fa5-db06-4832-84ee-38eb7e56d358)| ![image](https://github.com/user-attachments/assets/c799bab3-86db-43cc-9bed-a86068f8655a) |
=> style: align markdown width with container

blog/electron-33-0.md
=> chore: fix typo in v33 blog post

blog/electron-32-0.md
Refs https://github.com/electron/electron/issues/45396
Updates the Electron v32 release blog post to match the changes from https://github.com/electron/electron/pull/45412.
=> chore: add deletion of `databases` directory to 32 blog post

README.md
Small change here to update the Node version in the README to reflect the recent Node 22 upgrade
=> chore: bump node version in README

sidebars.js
Following https://github.com/electron/electron/pull/45639, let's add it to the right place in the sidebar. :)
=> feat: add docs style-guide to sidebar

src/css/custom.scss, src/pages/home/_index.module.scss
Summary
This PR fixes the issue where inline code (code elements) had a misaligned baseline on the Electron docs website when viewed on Mozilla 134.0.2 macOS.
Changes
Adjusted CSS styles to ensure proper alignment of inline code elements.
Verified the fix across different browsers to maintain consistency.
Testing
Tested on Mozilla 134.0.2 macOS ✅
Verified on Chrome and Safari to ensure no regressions ✅
Fixes #749
=> style: fix inline code baseline alignment

package.json, scripts/tasks/download-docs.ts, yarn.lock
Lets us drop dependencies we don't need and an `// eslint-disable`.
=> refactor: remove gunzip-maybe dependency

.github/workflows/check-blog-links.yml
This hasn't been completely tested E2E in a workflow but I tested locally and it looks good. 👍 We can get everything we need with `gh` CLI and a `jq` expression.
=> ci: restore `check-blog-links` workflow

src/css/custom.scss
Fixes: https://github.com/electron/website/issues/785
Added 0.5s background color transition when switching between light and dark themes. 
Changed the default light theme background (--ifm-background-color) from transparent to #fff (matching Node.js documentation) to enable the transition which wouldn't be possible with transparent background.
CC @erickzhao
=> feat: smooth background color transition when switching themes

.github/workflows/check-blog-links.yml, .github/workflows/pull-request.yml, .github/workflows/push-main.yml, .github/workflows/update-docs.yml, .github/workflows/update-i18n-deploy.yml
I'm not sure why we opted to use a separate Action for running `yarn install`, but this PR attempts to reduce our number of GHA dependencies by just calling `yarn` directly.
=> build: use `yarn install` directly

src/components/FiddleEmbed.module.scss
Small change that makes it so that adding other elements after a Fiddle embed has proper spacing.
=> style(fiddle-embed): add bottom margin

src/pages/community/index.tsx
I often send people to the community page when they ask questions in the issue tracker.
I noticed codebytere often also mentions the subreddit, so I thought we should mention it on the community page.
=> chore: link to subreddit from community page

docusaurus.config.ts
Reverts `NOTE` to `:::note` and keeps `IMPORTANT` as `:::info`. It's nice to distinguish between the two levels since we're probably going to be writing in GitHub-flavoured admonition syntax going forward.
=> style: revert to default mapping for admonitions

scripts/pre-build.ts, scripts/tasks/download-docs.ts
I broke this in https://github.com/electron/website/pull/744 and now this PR fixes it.
=> fix(pre-build): local checkout import

.github/workflows/push-main.yml, .github/workflows/update-i18n-deploy.yml, src/transformers/api-options-class.ts
Uses `azcopy sync --delete-destination` instead of `azcopy copy` so that stale files can be deleted from the website.
Uses the `--dry-run` flag so we don't mess anything up. Will trigger a workflow dispatch and then remove the flag in a follow-up PR if the dry run logs look good.
Unrelated MDX fix to make the i18n build more tolerant to faulty translation strings.
=> build: delete stale files on upload (dry-run)

.github/workflows/push-main.yml, .github/workflows/update-i18n-deploy.yml
Uses the `--compare-hash=MD5` flag to sync files that have changed based on their contents instead of last timestamp.
Also removes `--dry-run` so that we can test this live.
=> build: use MD5 compare for sync (no dry run)

.github/workflows/push-main.yml
Adds the ability to upload log files for the azcopy command and also ups the timeout limit on storage upload
=> build: add log upload, increase upload timeout

.github/workflows/push-main.yml, docusaurus.config.ts
This is new with Docusaurus 3.8 and potentially causes issues with the build: https://docusaurus.io/blog/releases/3.8#persistent-cache
=> build: disable rspack persistent cache

yarn.lock
Pulls in https://github.com/electron/lint-roller/pull/125 to avoid 429 Too Many Requests from the GitHub API.
=> ci: bump lint-roller

blog/electron-38-0.md
=> docs: improve bullet point in 38 blog post

blog/electron-38-0.md
The API was changed before the PR was merged. The release notes for the PR didn't get updated before merging.
I've updated the release notes after the PR was merged. This now also updates the blog post.
See the PR this entry is referring to: https://github.com/electron/electron/pull/47838
=> docs: fix incorrect v38 release notes bullet point
