electron/website

- scripts/tasks/md-fixers.js
The documentation in `electron/electron` uses the current format to
embed a fiddle:
```
```javascript fiddle='docs/fiddles/screen/fit-screen'
```
The new fiddle remark plugin uses:
```
```fiddle docs/fiddles/example
```
This PR updates all the old style to use the new one.
Ref https://github.com/electron/electronjs.org-new/pull/5
> build: transform fiddle markdown

- create-electron-documentation/readme.md
- scripts/tasks/download-docs.js
Merge only when this action is performed.
cc @MarshallOfSound
> chore: update `electron/electron` trunk name

- docusaurus.config.js
- package.json
- src/transformers/fiddle-embedder.js
- yarn.lock
See https://www.npmjs.com/package/@docusaurus/remark-plugin-npm2yarn for details
> feat: add npm2yarn plugin

- static.json
> fix: show docusaurus 404 page on error

- src/transformers/fiddle-embedder.js
This should generate the same links in fiddle as the previous site.
> fix: links to fiddles

- i18n/en-US/docusaurus-plugin-content-blog/options.json
- package.json
- yarn.lock
See release notes: https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.5
> build(deps): bump Docusaurus 2 to beta5

- blog/electron-14-0.md
https://twitter.com/KorbsStudio/status/1438216719277899779
> docs: add Electron 14 blog post

- blog/electron-15-0.md
First blog post on the new website repo!
Attn @sofianguy
Please add a comment for items you think we should highlight in the blog post; I'll also give your contributor access to my fork if you'd like to push to this PR directly.
⚠️ do not merge until the following are completed ⚠️
> chore: Electron 15 blog post

- src/css/custom.scss
> style: use default admonition code colors

- docusaurus.config.js
- package.json
- yarn.lock
Bumps the packages and fixes a small config setting affected by a breaking change.
> build(deps): bump Docusaurus 2 to beta-14

- docusaurus.config.js
> chore: disable versioned docs dropdown for now

- .github/workflows/push-others.yml
> build: remove user-defined GITHUB_TOKEN for versioned deploy

- docs/latest/api/browser-view.md
- docs/latest/api/browser-window.md
- docs/latest/api/session.md
- docs/latest/api/web-contents.md
> chore: manually pull in docs

- blog/2022-summer-of-code.md
This PR adds a blog post for Google Summer of Code!
Please check all links and make sure a) they work and b) they're public
> chore: summer of code blog post

- docusaurus.config.js
> feat(search): migrate to DocSearch V3

- .github/workflows/build-and-deploy.yml
- .github/workflows/update-i18n-deploy.yml
Moves to the new storage account
> build: use new az storage

- blog/s3-bucket-change.md
> blog: add new S3 migration post

- src/pages/fiddle/index.jsx
> refactor: improve linux download list for fiddle

- blog/electron-21-0.md
> chore: add some new features and api changes

- blog/autoupdating-electron-apps.md
> blog: fix typo in update-electron-app blog post

- sidebars.js
ref https://github.com/electron/electron/pull/35990
> chore: remove widevine doc from sidebar

- src/pages/apps/index.jsx
Fixed https://github.com/electron/electronjs.org-new/issues/261
> fix(showcase): force `en` locale compare

- package.json
- yarn.lock
https://docusaurus.io/blog/releases/2.2
> build(deps): upgrade docusaurus to 2.2.0

- blog/dec-quiet-month-22.md
First draft of the Quiet December Month blogpost for 2022 based off the original for 2021: https://www.electronjs.org/blog/a-quiet-place-21
If any working groups have any change requests for the "What will be the same in December or What will be different in December" section let me know! I can make revisions as necessary
Locally concerned everything looks ok. See [screenshot](https://user-images.githubusercontent.com/4099786/202060464-1e387e71-678e-48db-a9c6-52bf40993bf4.png) attached
> chore: December Quiet Month Blog Post

- docs/latest/api/app.md
- docs/latest/api/auto-updater.md
- docs/latest/api/browser-window.md
- docs/latest/api/client-request.md
- docs/latest/api/crash-reporter.md
- docs/latest/api/ipc-main.md
- docs/latest/api/push-notifications.md
- docs/latest/api/session.md
- docs/latest/api/structures/file-path-with-headers.md
- docs/latest/api/structures/notification-response.md
- docs/latest/api/structures/protocol-request.md
- docs/latest/api/structures/protocol-response.md
- docs/latest/api/structures/user-default-types.md
- docs/latest/api/system-preferences.md
- docs/latest/api/web-contents.md
- docs/latest/api/web-request.md
- docs/latest/api/webview-tag.md
- scripts/i18n-build.js
- scripts/tasks/md-fixers.js
- scripts/utils/execute.js
This PR fixes our website translation builds, I think?
> fix(i18n): remove unnecessary Docusaurus config hacks

- yarn.lock
Ref https://github.com/electron/website/pull/315
> chore: update @actions/core

- blog/windows-7-deprecation
Adds a blog post announcing Windows 7/8 deprecation.
> chore: windows 7 deprecation blog post

- .github/workflows/build-and-deploy.yml
- .github/workflows/push-main.yml
- .github/workflows/push-others.yml
- .github/workflows/update-docs-branch.yml
- .github/workflows/update-docs.yml
> fix(build): run `yarn build` for `en` builds

- sidebars.js
> fix: prune docs for electron 22

- package.json
Forgot to update the script call after migrating the whole thing to TS 🤦
> fix: use TypeScript i18n scripts

- .github/semantic.yml
- .github/workflows/semantic.yml
Refs https://github.com/electron/electron/pull/33857.
> chore: use action-semantic-pull-request

- package.json
Not me being forgetful again 😮‍💨 
ref https://github.com/electron/website/actions/runs/3963154967/jobs/6790676925
> fix: switch all package.json scripts to ts

- yarn.lock
> build: update dependencies to clean up yarn audit

- blog/electron-22-0.md
> fix(blog): update windows support info

- LICENSE
> chore: fill copyright notice in LICENSE

- scripts/tasks/create-sidebar.ts
- sidebars.js
This is a cute little trick to ensure that our generated code abides to our Prettier configuration. :)
> style(prebuild): apply prettier on sidebar gen

- src/plugins/governance/components/index.tsx
After #379 the governance page isn't rendering correctly.
> fix: correct syntax for optional WG chair

- .github/CODEOWNERS
> chore: set wg-outreach as owner of /blog/

- package.json
- yarn.lock
```sh
yarn upgrade @docusaurus/core@latest @docusaurus/plugin-google-analytics@latest @docusaurus/preset-classic@latest @docusaurus/remark-plugin-npm2yarn@latest @docusaurus/module-type-aliases@latest @docusaurus/types@latest
```
> build(deps): Docusaurus 2.4.0

- scripts/tasks/md-fixers.ts
This is so https://github.com/electron/electron/pull/34633 can land. The motivation is to be able to retain an inlined API structure in cases where it would otherwise be bad UX to put it behind an extra click in the docs, and where the hover preview is not a good fit, while allowing the API structure to be in a separate file that can be referenced from multiple locations. `BrowserWindowConstructorOptions` from that PR is a motivating example.
The goal is to inline the API structure in such a way that the resulting Markdown is identical to what it would be if the API structure was not pulled out into a separate file.
To that end this PR:
* Assumes that the API structure doc being inlined consists of:
* A `# Foo` header (although it allows it to be optional, and not necessarily on the first …
> feat: support inlining API structure links with ?inline query param

- .github/workflows/update-i18n-deploy.yml
Attempt to fix https://github.com/electron/website/actions/runs/4754033234/jobs/8446349254
> build: remove cache from i18n ci job

- blog/electron-24-0.md
> docs: update 24 blog post with 22 support info

- i18n/en/code.json
- i18n/en/docusaurus-plugin-content-docs/current.json
- i18n/en/docusaurus-theme-classic/footer.json
- i18n/en/docusaurus-theme-classic/navbar.json
> build(i18n): update write-translations

- sidebars.js
ref https://github.com/electron/electron/pull/38622
> fix: remove `azure-vm-setup` from sidebar

- README.md
> docs: document DocSearch functionality

- src/components/APIStructurePreview.tsx
- src/transformers/api-structure-previews.ts
> fix: links in API structure previews

- src/pages/home/_index.module.scss
> style: make `summary` components bold

- src/pages/fiddle/index.tsx
Signed-off-by: Robert Günzler <r@gnzler.io>
> feat: add appimage links to download page

- docusaurusConfig.ts
> chore: remove Forge v6 announcement banner

- .github/workflows/check-blog-links.yml
- package.json
- yarn.lock
We've had a few blog posts now where broken links slipped through, so let's add an automated check.
> ci: check links in blog post pull requests

- src/pages/home/_index.tsx
> fix: change the link to tailwindcss logo

- LICENSE
Updated license copyright year to **2024**
> docs: update license copyright

- .github/workflows/semantic.yml
- blog/2024-summer-of-code.md
Hey hey hey @electron/summer-of-code
> blog: GSOC 2024 announcement post

- blog/july-2016-roundup.md
Fixes one instance forgotten in #515
> chore: additional mdx fix

- .github/workflows/check-blog-links.yml
- .markdownlint.json
- package.json
- yarn.lock
> build: update @electron/lint-roller to 2.2.0

- create-electron-documentation/index.js
This script may not be getting usage at the moment, but noticed a chance to modernize it a bit.
> chore: modernize create-electron-documentation script

- README.md
> docs: update Node.js version in README

- package.json
- scripts/tasks/download-docs.ts
- src/plugins/governance/fetch-data.ts
- yarn.lock
Review with whitespace off, required some indentation.
> chore: remove got dependency in favor of built-in fetch

- src/css/custom.scss
Minimal lines of code to achieve the same effect I think?
Ref https://github.com/electron/website/pull/622#issuecomment-2285035680
Upside: no swizzling
Downside: these attribute selectors are brittle and Docusaurus considers them to be internal implementation details: https://docusaurus.io/docs/styling-layout#theme-class-names
> style: prettier blog sidebar styles

- docusaurus.config.ts
This pull request updates the social media icons across the website by replacing the Twitter text with the "X" text in the footer links.
Closes #625
> fix: update Twitter branding

- package.json
- yarn.lock
This doesn't make it fully clean, but closes a bunch
> build: update deps to clean audit

- .husky/pre-commit
- package.json
- yarn.lock
> build(dev-deps): update husky and lint-staged

- docusaurus.config.ts
https://bsky.app/profile/electronjs.org
> chore: add bsky account link

- src/theme/Footer/Layout/index.tsx
This got flagged while I was checking other things.
> chore: add alt text to footer logo images

- .github/workflows/push-main.yml
Adapted from https://github.com/docuactions/cache
> ci: store Docusaurus cache between builds

- yarn.lock
> build(deps): update express to partially clear audit

- blog/node-22-ecosystem-update.md
> chore: update Node 22 blog publish date to Jan 2025

- static/assets/apps/obsidian.svg
Fix #731 by updating the Obsidian icon.
> fix: Update Obsidian icon (#731)

- docusaurus.config.ts
Follow-up to https://github.com/electron/website/pull/698
> chore: add Node.js 22 announcement

- sidebars.js
- src/theme/DocSidebarItem/Link/index.tsx
- src/theme/DocSidebarItem/Link/styles.module.css
- src/theme/README.md
> feat: mark items as deprecated in sidebar

- src/components/APIStructurePreview.module.scss
Closes https://github.com/electron/website/issues/721
See the relevant preview: https://fix-api-structure-preview-ad.electron-website.pages.dev/docs/latest/api/crash-reporter#crashreportergetuploadedreports
> fix(api-structure-preview): adjust spacing styles

- src/util/featured-apps.ts
- static/assets/apps/oomol-studio.svg
This is a new app developed by our team.
> chore: add oomol studio to featured apps

- package.json
- yarn.lock
> build(dev-deps): bump tsx to partially clear audit

- blog/2025-summer-of-code.md
It's that time of the year again! Mostly just updated our 2024 blog post so keeping the authors the same.
> blog: GSoC 2025 announcement post

- .gitignore
- i18n/en/code.json
- i18n/en/docusaurus-plugin-content-docs/current.json
- i18n/en/docusaurus-theme-classic/footer.json
- i18n/en/docusaurus-theme-classic/navbar.json
I think this actually controls the copyright footer year unfortunately, so here's an update. 😮‍💨
> chore: update i18n website strings

- blog/electron-34-0.md
Might as well put the words I wrote to use haha
ref https://github.com/electron/website/pull/761#issuecomment-2702415768
> blog: add more colour to the v34 release post

- .github/PULL_REQUEST_TEMPLATE.md
Equivalent of https://github.com/electron/electron/pull/46316 for `electron/website`.
CC @electron/wg-community-safety
> chore: add PR template to discourage AI PRs

- .github/workflows/check-blog-links.yml
Follow-up to #783 which had this issue surfaced once it was actually run in CI.
> ci: properly set auth in `check-blog-links` workflow

- blog/electron-36-0.md
See https://github.com/electron/website/pull/801/files#r2072142491
> docs: fix class name in v36 blog post

- package.json
- yarn.lock
Bumping this again, because while this repo doesn't make use of any of the scripts from the package (at the moment), those are busted in v3.0.0 so it's best not to have a busted version here. Plus it drops some dependencies.
> build(dev-deps): update @electron/lint-roller to 3.1.1

- src/pages/community/index.tsx
As far as I understood, the Twitter profile is no longer active and all activity has shifted to Bluesky.
> chore: replace Twitter with Bluesky

- src/css/custom.scss
Changes the active style a little bit but fixes a little 2px misalignment with the navbar links.
> fix: proper alignment for navbar links

- src/pages/home/_index.module.scss
- src/pages/home/_index.tsx
> fix(home): make hero buttons responsive

- .github/workflows/push-main.yml
Follow up to #826 . Fixes the relative path for the azcopy binary
> build: fix path for azcopy dir

- .github/workflows/push-main.yml
> build: fix path for azcopy log storage

- .github/workflows/push-main.yml
- .github/workflows/update-i18n-deploy.yml
Finally found a pattern that worked. Also adds debug logging to the i18n build.
> build(azcopy): fix exclude pattern and always upload logs

- src/pages/home/_components/FeaturedAppsCarousel.module.scss
> fix(home): use pointer cursor for carousel links

- src/plugins/apps/index.ts
> chore: remove skype from favourite apps

- blog/electron-37-0.md
Attempt at fixing Crowdin parsing...
> fix: better table semantics in blog

- sidebars.js
This was added in E35 but we forgot to add it to the sidebar.
> fix: add ServiceWorkerMain to main process modules sidebar

- .github/workflows/audit-docs-version.yml
- .github/workflows/resolve-pr-release-versions.yml
There's no checkout so we can't read `.nvmrc`.
> ci: use specific Node.js version, not .nvmrc

- blog/electron-37-0.md
Seems the relative link here doesn't play nice with i18n.
> blog: fix image with i18n

- .github/workflows/audit-docs-version.yml
- .github/workflows/resolve-pr-release-versions.yml
Another follow-up, looks like this isn't just silently ignored if no `yarn.lock` is found. 🙃
> ci: remove cache option from setup-node

- sidebars.js
As in title. It's nice to be able to find these more quickly.
> chore: add utility process modules to sidebar
